// Code generated by 'micro gen' command.
// The temporary code used to ensure successful compilation!
// When the project is completed, it should be removed!

package logic

//import (
//	tp "github.com/henrylee2cn/teleport"
//
//	"github.com/xiaoenai/tp-template/account/args"
//	// "github.com/xiaoenai/tp-template/account/logic/model"
//	// "github.com/xiaoenai/tp-template/account/rerrs"
//)
//
//// 增加用户
//func V1_User_Set(ctx tp.PullCtx, arg *args.SetUserArgsV1) (*args.SetUserResultV1, *tp.Rerror) {
//	return new(args.SetUserResultV1), nil
//}
//
//// 根据ID获取user
//func V1_User_GetById(ctx tp.PullCtx, arg *args.GetUserByIdArgsV1) (*args.GetUserByIdResultV1, *tp.Rerror) {
//	return new(args.GetUserByIdResultV1), nil
//}
