user:
  srv:
    network: ""
    listen_address: :0
    outer_host: ""
    tls_cert_file: ""
    tls_key_file: ""
    default_session_age: 0s
    default_context_age: 0s
    slow_comet_duration: 500ms
    default_body_codec: ""
    print_detail: true
    count_time: true
    enable_heartbeat: true
  etcd:
    endpoints:
    - http://127.0.0.1:2379
    dial_timeout: 0s
    username: ""
    password: ""
  cli:
    network: ""
    local_ip: ""
    tls_cert_file: ""
    tls_key_file: ""
    default_session_age: 0s
    default_context_age: 0s
    default_dial_timeout: 0s
    failover: 0
    slow_comet_duration: 0s
    default_body_codec: ""
    print_detail: false
    count_time: false
    heartbeat_second: 0
    circuit_breaker:
      enable: false
      error_percentage: 0
      break_duration: 0s
  cache_expire: 24h0m0s
  log_level: TRACE
