// Code generated by 'micro gen' command.
// DO NOT EDIT!

package api

import (
	tp "github.com/henrylee2cn/teleport"

	"github.com/xiaoenai/tp-template/user/args"
	"github.com/xiaoenai/tp-template/user/logic"
)

// V1_User controller
type V1_User struct {
	tp.PullCtx
}

// Add handler
func (v *V1_User) Add(arg *args.AddUserArgsV1) (*args.AddUserResultV1, *tp.Rerror) {
	return logic.V1_User_Add(v.PullCtx, arg)
}

// 获取用户
func (v *V1_User) GetById(arg *args.GetUserByIdArgsV1) (*args.GetUserByIdResultV1, *tp.Rerror) {
	return logic.V1_User_GetById(v.PullCtx, arg)
}

// Get handler
func (v *V1_User) Get(arg *args.GetUserArgsV1) (*args.GetUserResultV1, *tp.Rerror) {
	return logic.V1_User_Get(v.PullCtx, arg)
}
