// Code generated by 'micro gen' command.
// The temporary code used to ensure successful compilation!
// When the project is completed, it should be removed!

package logic

//import (
//	tp "github.com/henrylee2cn/teleport"
//
//	"github.com/xiaoenai/tp-template/user/args"
//	// "github.com/xiaoenai/tp-template/user/logic/model"
//	// "github.com/xiaoenai/tp-template/user/rerrs"
//)
//
//// Add handler
//func V1_User_Add(ctx tp.PullCtx, arg *args.AddUserArgsV1) (*args.AddUserResultV1, *tp.Rerror) {
//	return new(args.AddUserResultV1), nil
//}
//
//// 获取用户
//func V1_User_GetById(ctx tp.PullCtx, arg *args.GetUserByIdArgsV1) (*args.GetUserByIdResultV1, *tp.Rerror) {
//	return new(args.GetUserByIdResultV1), nil
//}
//
//// Get handler
//func V1_User_Get(ctx tp.PullCtx, arg *args.GetUserArgsV1) (*args.GetUserResultV1, *tp.Rerror) {
//	return new(args.GetUserResultV1), nil
//}
