// Code generated by 'micro gen' command.
// DO NOT EDIT!

package sdk

import (
	"fmt"

	tp "github.com/henrylee2cn/teleport"
	"github.com/henrylee2cn/teleport/socket"
	micro "github.com/xiaoenai/tp-micro"
	"github.com/xiaoenai/tp-micro/discovery"
	"github.com/xiaoenai/tp-micro/model/etcd"

	"github.com/xiaoenai/tp-template/account/args"
	"github.com/xiaoenai/tp-template/plugin"
)

var _ = fmt.Sprintf
var client *micro.Client

// Init initializes client with configs.
func Init(cliConfig micro.CliConfig, etcdConfing etcd.EasyConfig) {
	client = micro.NewClient(
		cliConfig,
		discovery.NewLinker(etcdConfing),
	)
}

// InitWithClient initializes client with specified object.
func InitWithClient(cli *micro.Client) {
	client = cli
}

// 增加用户
func V1_User_Set(arg *args.SetUserArgsV1, setting ...socket.PacketSetting) (*args.SetUserResultV1, *tp.Rerror) {
	result := new(args.SetUserResultV1)
	rerr := client.Pull("/account/v1/user/set", arg, result, plugin.AddInnerAuth(setting...)).Rerror()
	return result, rerr
}

// 根据ID获取user
func V1_User_GetById(arg *args.GetUserByIdArgsV1, setting ...socket.PacketSetting) (*args.GetUserByIdResultV1, *tp.Rerror) {
	result := new(args.GetUserByIdResultV1)
	rerr := client.Pull("/account/v1/user/get_by_id", arg, result, plugin.AddInnerAuth(setting...)).Rerror()
	return result, rerr
}
