// Code generated by 'micro gen' command.
// DO NOT EDIT!

package args

import (
	"github.com/henrylee2cn/teleport/codec"
)

// EmptyStruct alias of type struct {}
type EmptyStruct = codec.PbEmpty

// AddUserResultV1 alias of type codec.PbEmpty
type AddUserResultV1 = codec.PbEmpty

// GetUserArgsV1 alias of type codec.PbEmpty
type GetUserArgsV1 = codec.PbEmpty

// AddUserArgsV1 comment...
type AddUserArgsV1 struct {
	Name string `json:"name"`
}

// GetUserByIdArgsV1 comment...
type GetUserByIdArgsV1 struct {
	Id int64 `param:"<query> <nonzero> <rerr:400:id不能为空>" json:"id"`
}

// GetUserByIdResultV1 comment...
type GetUserByIdResultV1 struct {
	Name        string `json:"name"`
	AccessToken string `json:"access_token"`
}

// GetUserResultV1 comment...
type GetUserResultV1 struct {
	Name string `json:"name"`
}
